apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-rolling
  labels:
    app: capstone-rolling
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-rolling
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-rolling
    spec:
      containers:
        - image: pmanu1977/capstone-rolling
          imagePullPolicy: Always
          name: capstone-rolling
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-rolling
  labels:
    app: capstone-rolling
spec:
  type: LoadBalancer
  selector:
    app: capstone-rolling
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
